#https://github.com/equinor/sdp-flux/blob/prod/prod/nginx-ingress/helm-release-patch.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  values:
    controller:
      service:
        loadBalancerIP: 51.120.76.229