#https://github.com/equinor/sdp-flux/blob/prod/prod/nginx-ingress/helm-release-patch.yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: default
spec:
  releaseName: nginx-ingress
  targetNamespace: default
  values:
    replicas: 1
